title: NBA analysis
description: some statistical analysis of basketball games
theme: just-the-docs
url: https://louisbanningtaylor.github.io/nba.website


aux_links:
  Template Repository: https://github.com/louisbanningtaylor/nba.website
